#include "config.h"
#include "../bigsize.c"
#include "../blinding.c"
#include "../hmac.c"
#include "../type_to_string.c"
#include <common/channel_id.h>
#include <common/setup.h>
#include <stdio.h>

#undef SUPERVERBOSE
#define SUPERVERBOSE printf
  #include "../blindedpath.c"

/* AUTOGENERATED MOCKS START */
/* Generated stub for amount_asset_is_main */
bool amount_asset_is_main(struct amount_asset *asset UNNEEDED)
{ fprintf(stderr, "amount_asset_is_main called!\n"); abort(); }
/* Generated stub for amount_asset_to_bro */
struct amount_bro amount_asset_to_bro(struct amount_asset *asset UNNEEDED)
{ fprintf(stderr, "amount_asset_to_bro called!\n"); abort(); }
/* Generated stub for amount_bro */
struct amount_bro amount_bro(u64 broneess UNNEEDED)
{ fprintf(stderr, "amount_bro called!\n"); abort(); }
/* Generated stub for amount_bro_add */
 bool amount_bro_add(struct amount_bro *val UNNEEDED,
				       struct amount_bro a UNNEEDED,
				       struct amount_bro b UNNEEDED)
{ fprintf(stderr, "amount_bro_add called!\n"); abort(); }
/* Generated stub for amount_bro_eq */
bool amount_bro_eq(struct amount_bro a UNNEEDED, struct amount_bro b UNNEEDED)
{ fprintf(stderr, "amount_bro_eq called!\n"); abort(); }
/* Generated stub for amount_bro_greater_eq */
bool amount_bro_greater_eq(struct amount_bro a UNNEEDED, struct amount_bro b UNNEEDED)
{ fprintf(stderr, "amount_bro_greater_eq called!\n"); abort(); }
/* Generated stub for amount_bro_sub */
 bool amount_bro_sub(struct amount_bro *val UNNEEDED,
				       struct amount_bro a UNNEEDED,
				       struct amount_bro b UNNEEDED)
{ fprintf(stderr, "amount_bro_sub called!\n"); abort(); }
/* Generated stub for amount_bro_to_asset */
struct amount_asset amount_bro_to_asset(struct amount_bro *bro UNNEEDED, const u8 *asset UNNEEDED)
{ fprintf(stderr, "amount_bro_to_asset called!\n"); abort(); }
/* Generated stub for amount_tx_fee */
struct amount_bro amount_tx_fee(u32 fee_per_kw UNNEEDED, size_t weight UNNEEDED)
{ fprintf(stderr, "amount_tx_fee called!\n"); abort(); }
/* Generated stub for fromwire_amount_mbro */
struct amount_mbro fromwire_amount_mbro(const u8 **cursor UNNEEDED, size_t *max UNNEEDED)
{ fprintf(stderr, "fromwire_amount_mbro called!\n"); abort(); }
/* Generated stub for fromwire_amount_bro */
struct amount_bro fromwire_amount_bro(const u8 **cursor UNNEEDED, size_t *max UNNEEDED)
{ fprintf(stderr, "fromwire_amount_bro called!\n"); abort(); }
/* Generated stub for fromwire_channel_id */
bool fromwire_channel_id(const u8 **cursor UNNEEDED, size_t *max UNNEEDED,
			 struct channel_id *channel_id UNNEEDED)
{ fprintf(stderr, "fromwire_channel_id called!\n"); abort(); }
/* Generated stub for fromwire_node_id */
void fromwire_node_id(const u8 **cursor UNNEEDED, size_t *max UNNEEDED, struct node_id *id UNNEEDED)
{ fprintf(stderr, "fromwire_node_id called!\n"); abort(); }
/* Generated stub for towire_amount_mbro */
void towire_amount_mbro(u8 **pptr UNNEEDED, const struct amount_mbro mbro UNNEEDED)
{ fprintf(stderr, "towire_amount_mbro called!\n"); abort(); }
/* Generated stub for towire_amount_bro */
void towire_amount_bro(u8 **pptr UNNEEDED, const struct amount_bro bro UNNEEDED)
{ fprintf(stderr, "towire_amount_bro called!\n"); abort(); }
/* Generated stub for towire_channel_id */
void towire_channel_id(u8 **pptr UNNEEDED, const struct channel_id *channel_id UNNEEDED)
{ fprintf(stderr, "towire_channel_id called!\n"); abort(); }
/* Generated stub for towire_node_id */
void towire_node_id(u8 **pptr UNNEEDED, const struct node_id *id UNNEEDED)
{ fprintf(stderr, "towire_node_id called!\n"); abort(); }
/* AUTOGENERATED MOCKS END */

static void json_strfield(const char *name, const char *val)
{
	printf("\t\"%s\": \"%s\",\n", name, val);
}

/* Updated each time, as we pretend to be Alice, Bob, Carol */
static const struct privkey *mykey;

static void test_ecdh(const struct pubkey *point, struct secret *ss)
{
	if (secp256k1_ecdh(secp256k1_ctx, ss->data, &point->pubkey,
			   mykey->secret.data, NULL, NULL) != 1)
		abort();
}

static void test_decrypt(const struct pubkey *blinding,
			 const u8 *enctlv,
			 const struct privkey *me,
			 const struct pubkey *expected_next_node,
			 const struct privkey *expected_next_blinding_priv)
{
	struct pubkey expected_next_blinding, dummy, next_node, next_blinding;
	struct secret ss;

	/* We don't actually have an onion, so we put some dummy */
	pubkey_from_privkey(me, &dummy);

	mykey = me;
	assert(unblind_onion(blinding, test_ecdh, &dummy, &ss));
	assert(decrypt_enctlv(blinding, &ss, enctlv, &next_node, &next_blinding));

	pubkey_from_privkey(expected_next_blinding_priv, &expected_next_blinding);
	assert(pubkey_eq(&next_blinding, &expected_next_blinding));
	assert(pubkey_eq(&next_node, expected_next_node));
}

static void test_final_decrypt(const struct pubkey *blinding,
			       const u8 *enctlv,
			       const struct privkey *me,
			       const struct pubkey *expected_alias,
			       const struct secret *expected_self_id)
{
	struct pubkey my_pubkey, dummy, alias;
	struct secret ss, *self_id;

	/* We don't actually have an onion, so we put some dummy */
	pubkey_from_privkey(me, &dummy);

	mykey = me;
	pubkey_from_privkey(me, &my_pubkey);
	assert(unblind_onion(blinding, test_ecdh, &dummy, &ss));
	assert(decrypt_final_enctlv(tmpctx, blinding, &ss, enctlv, &my_pubkey,
					 &alias, &self_id));

	assert(pubkey_eq(&alias, expected_alias));
	assert(secret_eq_consttime(self_id, expected_self_id));
}

int main(int argc, char *argv[])
{
	struct privkey alice, bob, carol, dave, blinding, override_blinding;
	struct pubkey alice_id, bob_id, carol_id, dave_id, blinding_pub, override_blinding_pub, alias;
	struct secret self_id;
	u8 *enctlv;

	common_setup(argv[0]);

	memset(&alice, 'A', sizeof(alice));
	memset(&bob, 'B', sizeof(bob));
	memset(&carol, 'C', sizeof(carol));
	memset(&dave, 'D', sizeof(dave));
	pubkey_from_privkey(&alice, &alice_id);
	pubkey_from_privkey(&bob, &bob_id);
	pubkey_from_privkey(&carol, &carol_id);
	pubkey_from_privkey(&dave, &dave_id);

	memset(&blinding, 5, sizeof(blinding));
	pubkey_from_privkey(&blinding, &blinding_pub);

	/* We output the JSON test vectors. */
	printf("[{");
	json_strfield("test name", "Simple encrypted_recipient_data for Alice, next is Bob");
	json_strfield("node_privkey",
		      type_to_string(tmpctx, struct privkey, &alice));
	json_strfield("node_id",
		      type_to_string(tmpctx, struct pubkey, &alice_id));
	json_strfield("blinding_secret",
		      type_to_string(tmpctx, struct privkey, &blinding));
	json_strfield("blinding",
		      type_to_string(tmpctx, struct pubkey, &blinding_pub));
	printf("\t\"encrypted_data_tlv\": {\n"
	       "\t\t\"next_node_id\": \"%s\"\n"
	       "\t},\n",
	       type_to_string(tmpctx, struct pubkey, &bob_id));

	enctlv = create_enctlv(tmpctx, &blinding, &alice_id, &bob_id,
			       0, NULL, &blinding, &alias);
	printf("\t\"encrypted_recipient_data_hex\": \"%s\"\n"
	       "},\n",
	       tal_hex(tmpctx, enctlv));

	test_decrypt(&blinding_pub, enctlv, &alice, &bob_id, &blinding);

	pubkey_from_privkey(&blinding, &blinding_pub);
	memset(&override_blinding, 7, sizeof(override_blinding));
	pubkey_from_privkey(&override_blinding, &override_blinding_pub);

	printf("{");
	json_strfield("test name",
		      "Blinding-key-override encrypted_recipient_data for Bob, next is Carol");
	json_strfield("node_privkey",
		      type_to_string(tmpctx, struct privkey, &bob));
	json_strfield("node_id",
		      type_to_string(tmpctx, struct pubkey, &bob_id));
	json_strfield("blinding_secret",
		      type_to_string(tmpctx, struct privkey, &blinding));
	json_strfield("blinding",
		      type_to_string(tmpctx, struct pubkey, &blinding_pub));
	printf("\t\"encrypted_data_tlv\": {\n"
	       "\t\t\"next_node_id\": \"%s\",\n"
	       "\t\t\"blinding\": \"%s\"\n"
	       "\t},\n",
	       type_to_string(tmpctx, struct pubkey, &carol_id),
	       type_to_string(tmpctx, struct privkey, &override_blinding));

	enctlv = create_enctlv(tmpctx, &blinding, &bob_id, &carol_id,
			       0, &override_blinding_pub, &blinding, &alias);
	printf("\t\"encrypted_recipient_data_hex\": \"%s\"\n"
	       "},\n",
	       tal_hex(tmpctx, enctlv));

	test_decrypt(&blinding_pub, enctlv, &bob, &carol_id, &override_blinding);

	/* That replaced the blinding */
	blinding = override_blinding;
	blinding_pub = override_blinding_pub;

	printf("{");
	json_strfield("test name", "Padded encrypted_recipient_data for Carol, next is Dave");
	json_strfield("node_privkey",
		      type_to_string(tmpctx, struct privkey, &carol));
	json_strfield("node_id",
		      type_to_string(tmpctx, struct pubkey, &carol_id));
	json_strfield("blinding_secret",
		      type_to_string(tmpctx, struct privkey, &blinding));
	json_strfield("blinding",
		      type_to_string(tmpctx, struct pubkey, &blinding_pub));
	printf("\t\"encrypted_data_tlv\": {\n"
	       "\t\t\"next_node_id\": \"%s\",\n"
	       "\t\t\"padding\": \"%s\"\n"
	       "\t},\n",
	       type_to_string(tmpctx, struct pubkey, &dave_id),
	       tal_hex(tmpctx, tal_arrz(tmpctx, u8, 35)));

	enctlv = create_enctlv(tmpctx, &blinding, &carol_id, &dave_id,
			       35, NULL, &blinding, &alias);
	printf("\t\"encrypted_recipient_data_hex\": \"%s\"\n"
	       "},\n",
	       tal_hex(tmpctx, enctlv));

	test_decrypt(&blinding_pub, enctlv, &carol, &dave_id, &blinding);

	for (size_t i = 0; i < sizeof(self_id); i++)
		self_id.data[i] = i+1;
	printf("{");
	json_strfield("test name", "Final enctlv for Dave");
	json_strfield("node_privkey",
		      type_to_string(tmpctx, struct privkey, &dave));
	json_strfield("node_id",
		      type_to_string(tmpctx, struct pubkey, &dave_id));
	json_strfield("blinding_secret",
		      type_to_string(tmpctx, struct privkey, &blinding));
	json_strfield("blinding",
		      type_to_string(tmpctx, struct pubkey, &blinding_pub));
	printf("\t\"encrypted_data_tlv\": {\n"
	       "\t\t\"self_id\": \"%s\"\n"
	       "\t},\n",
	       type_to_string(tmpctx, struct secret, &self_id));

	enctlv = create_final_enctlv(tmpctx, &blinding, &dave_id,
				     0, &self_id, &alias);

	printf("\t\"encrypted_recipient_data_hex\": \"%s\"\n",
	       tal_hex(tmpctx, enctlv));

	printf("}]\n");
	pubkey_from_privkey(&blinding, &blinding_pub);

	test_final_decrypt(&blinding_pub, enctlv, &dave, &alias, &self_id);
	common_shutdown();
}
